const data = {
    products: [
        {
            name: 'Nike Slim Shirt',
            slug: 'nike-slim-shirt',
            category: 'shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            desciption: 'high quality shirt',
        },
        {
            name: 'Addidas Fit Shirt',
            slug: 'addidas-fit-shirt',
            category: 'shirts',
            image: '/images/p2.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Addidas',
            rating: 4.5,
            numReview: 10,
            desciption: 'high quality shirt',
        },
        {
            name: 'Nike Slim pent',
            slug: 'nike-slim-pent',
            category: 'pent',
            image: '/images/p3.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            desciption: 'high quality pent',
        },
        {
            name: 'Addidas Fit Pent',
            slug: 'addidas-fit-pent',
            category: 'Pent',
            image: '/images/p4.jpg',
            price: 100,
            countInStock: 10,
            brand: 'Addidas',
            rating: 4.5,
            numReview: 10,
            desciption: 'high quality pent',
        },
    ],
};
export default data;